# This workflow will install dependencies, create coverage tests and run Pytest Coverage Commentator
# For more information see: https://github.com/coroo/pytest-coverage-commentator
name: pytest-coverage-commentator
on:
  pull_request:
    branches: 
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel
    - name: Install dependencies
      run: |
        pipenv install --deploy --dev
    - name: Move to flask folder
      run: |
        cd app

    - name: Build coverage file
      run: |
        pipenv run pytest --cache-clear --cov=app > pytest-coverage.txt
    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2
